const birdNames = [
    'Cuckoo Banana', 
    'Feather Duster', 
    'Flamingo Flamenco', 
    'Waddles', 'Quackmire', 
    'Penguin Pal', 
    'Captain Beaker', 
    'Dodo Dodo', 
    'Chirpy McChirpface', 
    'Tweetie Pie', 
    'The Beakfast Club', 
    'Owl Pellet', 
    'Birdie Sanders', 
    'Eagle McBeagleface', 
    'Fowl Ball', 
    'Robert Downey Jr.', 
    'Beaky Blinders', 
    'Hawkward', 
    'Swoop Dogg', 
    'Wingston Churchill', 
    'Seagullible', 
    'Toucan Dewitt', 
    'Buzz Aldrin', 
    'Mighty Beagle', 
    'Egg', 
    'Scramble', 
    'Colonel Sanders', 
    'Kookoo Kachoo', 
    'Birdman Cometh', 
    'Wingeth Fire', 
    'Pecking Order', 
    'Cheep Thrills', 
    'Billie Beakish', 
    'Stephen Squawking', 
    'Pelicant Even', 
    'Sparrow Fart', 
    'Falcon Punch', 
    'Orville Redenbird', 
    'Cloaca Spanks', 
    'Birdemic', 
    'Wingardium Leviosa', 
    'Early Bird', 
    'Feather Locklear', 
    'Tweetheart', 
    'Optimus Prime', 
    'Hummin Birb', 
    'Cat', 
    'Dog',
    "Dove Paloma",
    'Kanara Lark',
    'Kestrel Hawk',
    'Peng Laraline',
    'Faulkner Fowler',
    'Claravis Crane',
    'Talon Claw'
];

module.exports = birdNames